

INSERT INTO record (title, description, group_name) VALUES ('Project Alpha', 'Initial phase of the new initiative', 'Development');
INSERT INTO record (title, description, group_name) VALUES ('Meeting Minutes', 'Notes from the weekly standup', 'Administration');
INSERT INTO record (title, description, group_name) VALUES ('Budget Review', 'Quarterly financial analysis', 'Finance');
INSERT INTO record (title, description, group_name) VALUES ('New Hire Onboarding', 'Process documentation for HR', 'Human Resources');
INSERT INTO record (title, description, group_name) VALUES ('Server Maintenance', 'Scheduled downtime for updates', 'IT');
INSERT INTO record (title, description, group_name) VALUES ('Marketing Campaign', 'Summer promotion planning', 'Marketing');
INSERT INTO record (title, description, group_name) VALUES ('Product Roadmap', 'Upcoming features and releases', 'Product');
INSERT INTO record (title, description, group_name) VALUES ('Customer Feedback', 'Summary of recent surveys', 'Customer Service');
INSERT INTO record (title, description, group_name) VALUES ('Inventory Check', 'Monthly stock reconciliation', 'Operations');
INSERT INTO record (title, description, group_name) VALUES ('Training Module', 'New employee orientation guide', 'Human Resources');
INSERT INTO record (title, description, group_name) VALUES ('Code Review', 'Peer assessment of recent changes', 'Development');
INSERT INTO record (title, description, group_name) VALUES ('Sales Report', 'Monthly performance metrics', 'Sales');
INSERT INTO record (title, description, group_name) VALUES ('Office Supplies', 'Restocking order details', 'Administration');
INSERT INTO record (title, description, group_name) VALUES ('Risk Assessment', 'Evaluation of potential project risks', 'Management');
INSERT INTO record (title, description, group_name) VALUES ('Client Presentation', 'Slides for upcoming pitch', 'Sales');
INSERT INTO record (title, description, group_name) VALUES ('Bug Fixes', 'List of resolved issues in v2.1', 'Development');
INSERT INTO record (title, description, group_name) VALUES ('Team Building', 'Plans for annual retreat', 'Human Resources');
INSERT INTO record (title, description, group_name) VALUES ('API Documentation', 'Updated endpoints and usage guide', 'Development');
INSERT INTO record (title, description, group_name) VALUES ('Expense Report', 'Monthly reimbursement claims', 'Finance');
INSERT INTO record (title, description, group_name) VALUES ('Social Media Strategy', 'Content calendar for Q3', 'Marketing');
INSERT INTO record (title, description, group_name) VALUES ('Performance Reviews', 'Annual employee evaluations', 'Human Resources');
INSERT INTO record (title, description, group_name) VALUES ('Product Launch', 'Coordination plan for new release', 'Product');
INSERT INTO record (title, description, group_name) VALUES ('Security Audit', 'Findings from penetration testing', 'IT');
INSERT INTO record (title, description, group_name) VALUES ('Customer Retention', 'Strategies to reduce churn', 'Customer Service');
INSERT INTO record (title, description, group_name) VALUES ('Workflow Optimization', 'Process improvement suggestions', 'Operations');
INSERT INTO record (title, description, group_name) VALUES ('Legal Compliance', 'Review of recent regulations', 'Legal');
INSERT INTO record (title, description, group_name) VALUES ('Website Redesign', 'Mockups for homepage update', 'Design');
INSERT INTO record (title, description, group_name) VALUES ('Vendor Contracts', 'Renewal terms for suppliers', 'Procurement');
INSERT INTO record (title, description, group_name) VALUES ('Quality Assurance', 'Test cases for new features', 'Development');
INSERT INTO record (title, description, group_name) VALUES ('Employee Handbook', 'Updated policies and procedures', 'Human Resources');
INSERT INTO record (title, description, group_name) VALUES ('Market Analysis', 'Competitor landscape overview', 'Strategy');
INSERT INTO record (title, description, group_name) VALUES ('Customer Onboarding', 'Streamlined signup process', 'Customer Service');
INSERT INTO record (title, description, group_name) VALUES ('Data Migration', 'Plan for transitioning to new CRM', 'IT');
INSERT INTO record (title, description, group_name) VALUES ('Content Strategy', 'Editorial calendar for blog', 'Marketing');
INSERT INTO record (title, description, group_name) VALUES ('Agile Transformation', 'Roadmap for methodology adoption', 'Management');
INSERT INTO record (title, description, group_name) VALUES ('Sustainability Initiative', 'Proposal for reducing carbon footprint', 'Operations');
INSERT INTO record (title, description, group_name) VALUES ('User Research', 'Findings from recent usability tests', 'Design');
INSERT INTO record (title, description, group_name) VALUES ('Partnership Agreement', 'Terms for new strategic alliance', 'Business Development');
INSERT INTO record (title, description, group_name) VALUES ('Disaster Recovery', 'Procedures for business continuity', 'IT');
INSERT INTO record (title, description, group_name) VALUES ('Employee Engagement', 'Results of satisfaction survey', 'Human Resources');
INSERT INTO record (title, description, group_name) VALUES ('Product Backlog', 'Prioritized list of upcoming work', 'Product');
INSERT INTO record (title, description, group_name) VALUES ('Cost Reduction', 'Identified areas for optimization', 'Finance');
INSERT INTO record (title, description, group_name) VALUES ('Brand Guidelines', 'Updated visual identity standards', 'Marketing');
INSERT INTO record (title, description, group_name) VALUES ('Compliance Training', 'Mandatory course materials', 'Legal');
INSERT INTO record (title, description, group_name) VALUES ('Feature Requests', 'Compilation of user suggestions', 'Product');
INSERT INTO record (title, description, group_name) VALUES ('Talent Acquisition', 'Strategies for attracting top candidates', 'Human Resources');
INSERT INTO record (title, description, group_name) VALUES ('Innovation Workshop', 'Ideation session outcomes', 'Research and Development');
INSERT INTO record (title, description, group_name) VALUES ('Customer Journey', 'Mapping of user interactions', 'Customer Service');
INSERT INTO record (title, description, group_name) VALUES ('Legacy System Retirement', 'Decommissioning plan for old software', 'IT');